version: "3"

services:
    localstack:
        container_name: localstack-container
        image: localstack/localstack
        ports:
            - 4572:4572
        environment:
            - SERVICES=s3:4572, sqs:4576, sns:4575
            - HOSTNAME=localhost
            - AWS_ACCESS_KEY_ID=foobar
            - AWS_SECRET_ACCESS_KEY=foobar
        networks:
            - dockernet

    scrapper:
        container_name: scrapper-container
        build: .
        volumes:
            - ./:/app
        ports: 
            - 5000:5000
        depends_on: 
            - localstack
        networks: 
            - dockernet
networks: 
    dockernet: