version: "3"

services:
    localstack:
        container_name: localstack-container
        image: localstack/localstack
        ports:
            - 4570-4577:4570-4577
            - 8080:8080
        environment:
            - SERVICES=s3:4572, sqs:4576, sns:4575
        networks:
            - dockernet

    scrapper:
        container_name: scrapper-container
        build: ./scrapper
        volumes:
            - ./scrapper:/app
            - ~/.aws:/root/.aws
        ports: 
            - 5000:5000
        environment: 
            - AWS_ACCESS_KEY_ID=foobar
            - AWS_SECRET_ACCESS_KEY=foobar
            - region=us-east-1
            - output=json
        depends_on: 
            - localstack
        networks: 
            - dockernet
    
    mlcore:
        container_name: mlcore-container
        build: ./mlcore
        volumes:
            - ./mlcore:/app
            - ~/.aws:/root/.aws
        ports:
            - 6543:6543
        depends_on: 
            - localstack
        networks: 
            - dockernet

    frontend:
        container_name: frontend-container
        volumes:
            - ./frontend:/app
        build: ./frontend
        ports: 
            - 4321:80
        depends_on: 
            - localstack
            - scrapper
            - mlcore
        networks: 
            - dockernet
networks: 
    dockernet:
        driver: bridge